ALTER TABLE pickings
  ADD COLUMN IF NOT EXISTS transporter   VARCHAR(50),
  ADD COLUMN IF NOT EXISTS order_type    VARCHAR(10) DEFAULT 'courier',
  ADD COLUMN IF NOT EXISTS voucher_qty   INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS invoice_date  TIMESTAMP,
  ADD COLUMN IF NOT EXISTS print_date    TIMESTAMP;
